# Generated by Django 4.2.30 on 2026-05-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_municipio', models.CharField(max_length=10, unique=True, verbose_name='Código IBGE')),
                ('no_municipio', models.CharField(max_length=120, verbose_name='Nome')),
                ('uf', models.CharField(default='SP', max_length=2)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ['no_municipio'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('variavel_alvo', models.CharField(max_length=60)),
                ('n_obs', models.IntegerField()),
                ('n_features', models.SmallIntegerField()),
                ('mediana_alvo', models.FloatField()),
                ('log_acuracia', models.FloatField()),
                ('log_auc', models.FloatField()),
                ('log_auc_cv', models.FloatField()),
                ('rf_acuracia', models.FloatField()),
                ('rf_auc', models.FloatField()),
                ('rf_auc_cv', models.FloatField()),
                ('top3_features', models.TextField()),
            ],
            options={
                'verbose_name': 'Resultado do modelo',
                'verbose_name_plural': 'Resultados dos modelos',
                'ordering': ['-rf_auc'],
            },
        ),
        migrations.CreateModel(
            name='ClusterMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_num', models.SmallIntegerField(verbose_name='Cluster')),
                ('cluster_label', models.CharField(max_length=30, verbose_name='Perfil')),
                ('inse_medio', models.FloatField(blank=True, null=True)),
                ('abandono_medio', models.FloatField(blank=True, null=True)),
                ('ideb_medio', models.FloatField(blank=True, null=True)),
                ('gasto_medio', models.FloatField(blank=True, null=True)),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='education.municipio')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['cluster_num', 'municipio'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('abandono_med_total', models.FloatField(blank=True, null=True)),
                ('abandono_fund_total', models.FloatField(blank=True, null=True)),
                ('abandono_med_1serie', models.FloatField(blank=True, null=True)),
                ('abandono_med_2serie', models.FloatField(blank=True, null=True)),
                ('abandono_med_3serie', models.FloatField(blank=True, null=True)),
                ('ideb_fund_ai', models.FloatField(blank=True, null=True)),
                ('ideb_fund_af', models.FloatField(blank=True, null=True)),
                ('ideb_medio', models.FloatField(blank=True, null=True)),
                ('saeb_5_lp', models.FloatField(blank=True, null=True)),
                ('saeb_5_mt', models.FloatField(blank=True, null=True)),
                ('saeb_9_lp', models.FloatField(blank=True, null=True)),
                ('saeb_9_mt', models.FloatField(blank=True, null=True)),
                ('saeb_12_lp', models.FloatField(blank=True, null=True)),
                ('saeb_12_mt', models.FloatField(blank=True, null=True)),
                ('enem_media_geral', models.FloatField(blank=True, null=True)),
                ('enem_media_mt', models.FloatField(blank=True, null=True)),
                ('enem_media_cn', models.FloatField(blank=True, null=True)),
                ('enem_media_ch', models.FloatField(blank=True, null=True)),
                ('enem_media_lc', models.FloatField(blank=True, null=True)),
                ('enem_media_redacao', models.FloatField(blank=True, null=True)),
                ('enem_participantes', models.IntegerField(blank=True, null=True)),
                ('gasto_aluno', models.FloatField(blank=True, null=True)),
                ('desp_edu_paga', models.FloatField(blank=True, null=True)),
                ('pib_percapita', models.FloatField(blank=True, null=True)),
                ('renda_percapita', models.FloatField(blank=True, null=True)),
                ('inse', models.FloatField(blank=True, null=True)),
                ('taxa_analfabetismo', models.FloatField(blank=True, null=True)),
                ('bf_media_mensal', models.FloatField(blank=True, null=True)),
                ('bf_por_aluno', models.FloatField(blank=True, null=True)),
                ('in_agua_potavel', models.FloatField(blank=True, null=True)),
                ('in_esgoto_rede_publica', models.FloatField(blank=True, null=True)),
                ('in_biblioteca', models.FloatField(blank=True, null=True)),
                ('in_laboratorio_informatica', models.FloatField(blank=True, null=True)),
                ('in_internet', models.FloatField(blank=True, null=True)),
                ('in_quadra_esportes', models.FloatField(blank=True, null=True)),
                ('in_refeitorio', models.FloatField(blank=True, null=True)),
                ('tdi_med_total', models.FloatField(blank=True, null=True)),
                ('tdi_fund_total', models.FloatField(blank=True, null=True)),
                ('afd_med_adequado', models.FloatField(blank=True, null=True)),
                ('afd_fund_adequado', models.FloatField(blank=True, null=True)),
                ('qt_mat_bas', models.FloatField(blank=True, null=True)),
                ('qt_mat_fund', models.FloatField(blank=True, null=True)),
                ('qt_mat_med', models.FloatField(blank=True, null=True)),
                ('qt_doc_med', models.FloatField(blank=True, null=True)),
                ('aluno_doc_med', models.FloatField(blank=True, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='education.municipio')),
            ],
            options={
                'verbose_name': 'Indicador anual',
                'verbose_name_plural': 'Indicadores anuais',
                'ordering': ['municipio', 'ano'],
                'unique_together': {('municipio', 'ano')},
            },
        ),
    ]
